---
abstract: 'yet another CPAN mirror aka DarkPAN repository manager'
author:
  - 'Tokuhiro Matsuno <tokuhirom AAJKLFJEF GMAIL COM>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0.96
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: OrePAN
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  CPAN::DistnameInfo: 0
  Cwd: 0
  File::Basename: 0
  File::Find: 0
  File::Temp: 0
  File::Which: 0
  IO::Zlib: 0
  JSON: 2.27
  LWP::UserAgent: 0
  List::MoreUtils: 0
  Log::Minimal: 0.02
  Mouse: 0
  Path::Class: 0
  YAML::Tiny: 0
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
version: 0.06
